Vagrant.configure("2") do |config|
  config.vm.box = "igormedo/devops-course-szte"

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.synced_folder "./", "/data"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
    vb.name = "szte-devops"
  end

  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
  config.ssh.insert_key = true
end