---
- hosts: 127.0.0.1
  connection: local
  become: yes
  gather_facts: yes

  roles:
    - role: geerlingguy.ntp
      ntp_timezone: UTC
      ntp_manage_config: true
      ntp_servers:
        - "pool.ntp.org iburst"

  tasks:
    # non system related extra packages not covered by cloud-init
    - apt: "name={{ item }} state=present"
      with_items:
        - vim
        - nano
        - joe
        - rsync
        - git
        - wget
        - curl
        - build-essential
        - bzip2
        - mc
        - htop
        - tree
